# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4fbc8b69118eac3b828f249bda6277956068e1b29fd8f9c8946936409edfbbb4c08c1623bdd9714497465917c079ef35e4e960bfb6fbdeb94d51ca611de29c9

test:
  secret_key_base: 0c78aba69016d524d122983b3701fb3adb3938b5c503397c2962d14f2a49455614d07b13ce430461df0a25b418dcba1bf098fa77bea7b87cd51e5239ca5c99ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
